### ISSUE TITLE
How to use standard in conjunction with eslint-config-standard-react

### ISSUE THREAD

**Issue by mrchief** [feross/standard-react#13] opened 2017-05-08 21:43 UTC
How does one use standard in conjunction with eslint-config-standard-react? Add eslintrc and extend it with  eslint-config-standard-react? Isn't that going against the philosophy of standard (no config, no eslintrc)?

**Comment by feross** [comment] 2017-06-22 02:49
Dupe of https://github.com/feross/standard/issues/885

**Closed as completed by feross** 2017-06-22 02:49 UTC
